// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmoPeGDxbqMzBHRk1s0YVv3FYZEipNDdE',
    appId: '1:396040374256:web:6814bf34eaa72b72e73f35',
    messagingSenderId: '396040374256',
    projectId: 'nation-forge-c1a12',
    authDomain: 'nation-forge-c1a12.firebaseapp.com',
    storageBucket: 'nation-forge-c1a12.firebasestorage.app',
    measurementId: 'G-CSL43QCZL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqXBqdvCB0PQdJvJANhaoaFkAr1iV6qyc',
    appId: '1:396040374256:android:41e131cb6dbc6c5ae73f35',
    messagingSenderId: '396040374256',
    projectId: 'nation-forge-c1a12',
    storageBucket: 'nation-forge-c1a12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUr4kC4bfy8NjcUnYsxtE-R3x37tkHob0',
    appId: '1:396040374256:ios:6acb007a4e287c3ae73f35',
    messagingSenderId: '396040374256',
    projectId: 'nation-forge-c1a12',
    storageBucket: 'nation-forge-c1a12.firebasestorage.app',
    androidClientId: '396040374256-0h7gc8ndq22m7g7if4venkn65e20a2ug.apps.googleusercontent.com',
    iosClientId: '396040374256-asbochrnd4nts86sjalova0sng2o3ddu.apps.googleusercontent.com',
    iosBundleId: 'com.rubendev.nationForge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUr4kC4bfy8NjcUnYsxtE-R3x37tkHob0',
    appId: '1:396040374256:ios:6acb007a4e287c3ae73f35',
    messagingSenderId: '396040374256',
    projectId: 'nation-forge-c1a12',
    storageBucket: 'nation-forge-c1a12.firebasestorage.app',
    androidClientId: '396040374256-0h7gc8ndq22m7g7if4venkn65e20a2ug.apps.googleusercontent.com',
    iosClientId: '396040374256-asbochrnd4nts86sjalova0sng2o3ddu.apps.googleusercontent.com',
    iosBundleId: 'com.rubendev.nationForge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmoPeGDxbqMzBHRk1s0YVv3FYZEipNDdE',
    appId: '1:396040374256:web:275ce7537c7bbfdee73f35',
    messagingSenderId: '396040374256',
    projectId: 'nation-forge-c1a12',
    authDomain: 'nation-forge-c1a12.firebaseapp.com',
    storageBucket: 'nation-forge-c1a12.firebasestorage.app',
    measurementId: 'G-0W62WQN0QV',
  );
}
